version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:5.0.4
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  flask_app:
    build:
      context: "./app"
    ports:
      - 5000:5000 # app port
    restart: always
      
